# Copyright (C) V3 Smart Technologies. All Rights Reserved.
#
# NOTICE:  Proprietary and confidential. This is the Intellectual Property
# of V3 Smart Technologies Pte Ltd and is not to be used, disclosed or
# duplicated, either in part or in entirety except with the written approval
# of V3 Smart Technologies Pte Ltd.
# ----------------------------------------------------------------------------------------------------
#
# app information...
#
appTitle=V3NITY
appName=FMS WAM
appVersion=1.0.0
appCompany=Powered by V3 Smart Technologies Pte. Ltd. fka V3 Teletech Pte. Ltd.
#appRequestProtocol=http
#appRequestHost=203.125.7.36
#appRequestPort=8080
appRequestProtocol=https
appRequestHost=rsqjms.v3nity.com
appRequestPort=8080
#appRequestHost=rsqjms.v3nity.com/
#appRequestPort=80
appDataSource=java:comp/env/jdbc/v3nityResus
#
# sender email configurations...
#
emailHost=mail.v3smarttech.com
emailPort=25
emailSender=support@v3smarttech.com
emailAuthenticate=yes
emailUsername=support@v3smarttech.com
emailPassword=V#Support1234
#
# comms server configurations...
#
gprsServerIp=192.168.88.198
gprsServerPort=9000
gprsServerIpTcp=192.168.88.198
gprsServerPortTcp=8880
smsUrl=http://smsgw.mmea.mes.syniverse.com/sms.php?id=22271&pw=m8MAxthI&snr=~sender~&dnr=%2b~phno~&msg=~msg~
pnUrl=http://127.0.0.1/PushNotification/Broadcast
#
# product updates email addresses. used by internal...
#
productUpdateRecipient=
productUpdateRecipientCC=
productUpdateRecipientBCC=
#
# to disable all listeners...
#
disableListener=0
#
# system file logging...
#
sysLogFile=no
sysLogLimit=10000000
#
# system remote logging...
#
sysLogRemote=no
sysLogRemoteHost=localhost
sysLogRemotePort=7000
#
# enabling types of message log...
#
sysLogError=yes
sysLogInfo=yes
sysLogDebug=yes
#
# system log controller request...
#
sysLogReq=yes
#
# interval in seconds to run gc...
#
gcInterval=7200
#
# the path for facial images training...
#
frPath=C:\\facial
webappName=v3nity2